# Generated by Django 3.2.11 on 2022-05-30 14:02

import django.db.models.deletion
import django.utils.timezone
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media", "0002_initial"),
        ("wagtailcore", "0066_collection_management_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsItemPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "paragraph",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "paragraph",
                                            wagtail.core.blocks.RichTextBlock(
                                                default="",
                                                features=[
                                                    "bold",
                                                    "italic",
                                                    "h2",
                                                    "h3",
                                                    "h4",
                                                    "h5",
                                                    "ol",
                                                    "ul",
                                                    "link",
                                                    "document",
                                                    "embed",
                                                ],
                                                label="Paragraph",
                                                required=True,
                                            ),
                                        )
                                    ]
                                ),
                            ),
                            (
                                "image",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="Image", required=True
                                            ),
                                        )
                                    ]
                                ),
                            ),
                            (
                                "quote",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "quote",
                                            wagtail.core.blocks.TextBlock(
                                                default="", label="Quote", required=True
                                            ),
                                        ),
                                        (
                                            "attribution",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="Attribution",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        verbose_name="Body",
                    ),
                ),
                (
                    "publish_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Publish date"
                    ),
                ),
            ],
            options={
                "verbose_name": "News item",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="NewsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "News",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "heading",
                    models.TextField(
                        blank=True, default="Heading", verbose_name="Heading"
                    ),
                ),
                (
                    "gallery",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "card",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.core.blocks.TextBlock(
                                                default="",
                                                label="Title",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "page",
                                            wagtail.core.blocks.PageChooserBlock(
                                                label="Page",
                                                page_type=[],
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="Image", required=False
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        verbose_name="Gallery",
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="media.customimage",
                        verbose_name="Hero image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Homepage",
            },
            bases=("wagtailcore.page",),
        ),
    ]
